const questionBank = [
  { category: 'Shop Safety', prompt: 'Before raising a vehicle, your first step is to:', choices: ['Check lift points and balance', 'Rev engine to warm up', 'Remove spark plugs', 'Bleed brakes'], correct: 'Check lift points and balance', explanation: 'Correct lift placement prevents vehicle falls.', difficulty: 'Easy' },
  { category: 'Shop Safety', prompt: 'Best eye protection for grinding is:', choices: ['Face shield or safety glasses', 'Baseball cap', 'Shop rag', 'Latex gloves'], correct: 'Face shield or safety glasses', explanation: 'Grinding throws sparks and debris toward the face.', difficulty: 'Easy' },
  { category: 'Tools & Equipment', prompt: 'Final wheel lug tightening should use a:', choices: ['Torque wrench', 'Pry bar', 'Impact only', 'Test light'], correct: 'Torque wrench', explanation: 'Torque specs prevent warped rotors and wheel damage.', difficulty: 'Easy' },
  { category: 'Tools & Equipment', prompt: 'Voltage is measured with a meter connected:', choices: ['In parallel', 'In series', 'At the fuse only', 'At battery negative only'], correct: 'In parallel', explanation: 'Voltage compares electrical potential between two points.', difficulty: 'Easy' },
  { category: 'Vehicle Maintenance', prompt: 'Why follow maintenance schedules?', choices: ['Reduce failures and extend life', 'Increase tire pressure', 'Disable warning lights', 'Avoid inspections'], correct: 'Reduce failures and extend life', explanation: 'Preventive service lowers breakdown risk.', difficulty: 'Easy' },
  { category: 'Vehicle Maintenance', prompt: 'Engine oil is best checked:', choices: ['On level ground using procedure', 'While driving', 'With radiator cap off', 'Only after rain'], correct: 'On level ground using procedure', explanation: 'Consistent method gives accurate level reading.', difficulty: 'Easy' },
  { category: 'Fluids', prompt: 'Low brake fluid can indicate:', choices: ['Possible leak or pad wear', 'Good battery health', 'Overfilled coolant', 'Worn wiper blades'], correct: 'Possible leak or pad wear', explanation: 'Investigate cause, don\u2019t just top off and ignore.', difficulty: 'Medium' },
  { category: 'Fluids', prompt: 'Never open a hot radiator cap because:', choices: ['System is pressurized and can burn you', 'Battery may drain', 'Tires may deflate', 'ABS may set a code'], correct: 'System is pressurized and can burn you', explanation: 'Hot coolant can spray out dangerously.', difficulty: 'Easy' },
  { category: 'Tires', prompt: 'Regular tire rotation helps:', choices: ['Even tread wear', 'Increase alternator output', 'Lower oil pressure', 'Calibrate TPMS'], correct: 'Even tread wear', explanation: 'Rotation spreads load patterns across positions.', difficulty: 'Easy' },
  { category: 'Tires', prompt: 'Uneven edge wear usually suggests:', choices: ['Alignment concern', 'Overcharged battery', 'Bad thermostat', 'Dirty fuel'], correct: 'Alignment concern', explanation: 'Toe/camber can wear one shoulder quickly.', difficulty: 'Medium' },
  { category: 'Brakes Basics', prompt: 'Spongy brake pedal most often means:', choices: ['Air in hydraulic system', 'New pads installed', 'Tight wheel nuts', 'Good booster'], correct: 'Air in hydraulic system', explanation: 'Air compresses and softens pedal feel.', difficulty: 'Easy' },
  { category: 'Brakes Basics', prompt: 'ABS mainly helps by:', choices: ['Reducing wheel lock during hard stops', 'Increasing engine power', 'Charging battery', 'Cooling rotors'], correct: 'Reducing wheel lock during hard stops', explanation: 'ABS helps keep steering control while braking.', difficulty: 'Medium' },
  { category: 'Batteries', prompt: 'A resting battery near 12.6V is usually:', choices: ['Near fully charged', 'Completely failed', 'Overcharging', 'Shorted starter'], correct: 'Near fully charged', explanation: '12.6V is a common full-charge reference.', difficulty: 'Easy' },
  { category: 'Batteries', prompt: 'Corroded battery terminals cause:', choices: ['High resistance and poor cranking', 'Higher fuel pressure', 'Coolant leaks', 'Better charging'], correct: 'High resistance and poor cranking', explanation: 'Corrosion restricts current flow.', difficulty: 'Easy' },
  { category: 'Starting Basics', prompt: 'Single click, no crank often points to:', choices: ['Weak battery/cable/starter issue', 'Good starter draw', 'Overfilled engine oil', 'Low tire tread'], correct: 'Weak battery/cable/starter issue', explanation: 'Start with battery state and cable checks.', difficulty: 'Medium' },
  { category: 'Starting Basics', prompt: 'Starter motor purpose is to:', choices: ['Crank engine for starting', 'Charge battery', 'Cool radiator', 'Run fuel pump continuously'], correct: 'Crank engine for starting', explanation: 'It spins the crankshaft until combustion starts.', difficulty: 'Easy' },
  { category: 'Charging Basics', prompt: 'Normal charging voltage running is about:', choices: ['13.5\u201314.8 volts', '10\u201311 volts', '12.0 exactly', '16.5 volts'], correct: '13.5\u201314.8 volts', explanation: 'Most systems regulate in this range.', difficulty: 'Easy' },
  { category: 'Charging Basics', prompt: 'Battery warning light on while running suggests:', choices: ['Charging system fault', 'Full fuel tank', 'Correct tire pressure', 'Normal operation'], correct: 'Charging system fault', explanation: 'Check belt, wiring, alternator output.', difficulty: 'Easy' },
  { category: 'Basic Electrical', prompt: 'Ohm\u2019s law is:', choices: ['V = I \u00d7 R', 'I = V \u00d7 W', 'R = I \u00f7 V', 'V = R \u00f7 I'], correct: 'V = I \u00d7 R', explanation: 'Core relationship between voltage, current, resistance.', difficulty: 'Easy' },
  { category: 'Basic Electrical', prompt: 'Continuity testing should be done with power:', choices: ['Off', 'At idle', 'At full charge', 'At high RPM'], correct: 'Off', explanation: 'De-energize circuit before ohms/continuity checks.', difficulty: 'Easy' },
  { category: 'Cooling Basics', prompt: 'Thermostat stuck closed usually causes:', choices: ['Fast overheating', 'Noisy alternator only', 'Low brake fluid', 'Better MPG'], correct: 'Fast overheating', explanation: 'Coolant cannot circulate through radiator.', difficulty: 'Easy' },
  { category: 'Cooling Basics', prompt: 'Milky engine oil may indicate:', choices: ['Coolant contamination', 'Normal break-in', 'Fresh fuel', 'Clean combustion'], correct: 'Coolant contamination', explanation: 'Coolant and oil emulsion looks milky.', difficulty: 'Medium' },
  { category: 'Belts & Hoses', prompt: 'A cracked serpentine belt can lead to:', choices: ['Charging and accessory issues', 'Higher compression', 'Better steering feel', 'Lower emissions instantly'], correct: 'Charging and accessory issues', explanation: 'Belt drives alternator and accessories.', difficulty: 'Easy' },
  { category: 'Belts & Hoses', prompt: 'Soft swollen coolant hose may mean:', choices: ['Hose deterioration', 'Strong battery', 'Perfect coolant flow', 'Normal by design'], correct: 'Hose deterioration', explanation: 'Aged hoses can fail under pressure.', difficulty: 'Easy' },
  { category: 'Engine Performance Basics', prompt: 'Vacuum leaks often cause:', choices: ['Lean idle and rough running', 'Overfilled crankcase', 'Strong battery', 'Cold AC vent'], correct: 'Lean idle and rough running', explanation: 'Unmetered air upsets air-fuel balance.', difficulty: 'Medium' },
  { category: 'Engine Performance Basics', prompt: 'Before replacing parts for misfire code, first:', choices: ['Verify basics: spark, fuel, compression', 'Replace PCM', 'Change tires', 'Flush coolant'], correct: 'Verify basics: spark, fuel, compression', explanation: 'Test evidence first, parts later.', difficulty: 'Medium' },
  { category: 'Warning Lights', prompt: 'Check engine light means:', choices: ['A fault was detected and should be diagnosed', 'Oil was just changed', 'Tires are aligned', 'Brake pads are new'], correct: 'A fault was detected and should be diagnosed', explanation: 'Use scan data and testing to find root cause.', difficulty: 'Easy' },
  { category: 'Warning Lights', prompt: 'TPMS light usually relates to:', choices: ['Tire pressure issue', 'Alternator failure', 'Radiator cap leak', 'Misfire'], correct: 'Tire pressure issue', explanation: 'Check and set tire pressures first.', difficulty: 'Easy' },
  { category: 'Scan Tool Basics', prompt: 'Freeze frame data shows:', choices: ['Conditions when code set', 'Future failures', 'Repair costs', 'Warranty expiration'], correct: 'Conditions when code set', explanation: 'Snapshot helps recreate fault context.', difficulty: 'Medium' },
  { category: 'Scan Tool Basics', prompt: 'Live data is useful because it:', choices: ['Shows sensor values in real time', 'Replaces all testing', 'Deletes all codes', 'Charges battery faster'], correct: 'Shows sensor values in real time', explanation: 'Compare sensor behavior to expected values.', difficulty: 'Easy' },
  { category: 'DTC Basics', prompt: 'DTC stands for:', choices: ['Diagnostic Trouble Code', 'Drive Train Command', 'Data Timing Circuit', 'Digital Test Control'], correct: 'Diagnostic Trouble Code', explanation: 'Standard term for stored fault code.', difficulty: 'Easy' },
  { category: 'DTC Basics', prompt: 'A pending code means:', choices: ['Fault seen but not matured yet', 'Vehicle fixed', 'No issue found', 'Battery disconnected'], correct: 'Fault seen but not matured yet', explanation: 'May require another drive cycle to set hard code.', difficulty: 'Medium' },
  { category: 'CCC Thinking', prompt: 'In concern-cause-correction, \u201cconcern\u201d is:', choices: ['Customer-reported symptom', 'Part to replace', 'Repair bill', 'Test equipment list'], correct: 'Customer-reported symptom', explanation: 'Start by verifying the exact concern.', difficulty: 'Easy' },
  { category: 'CCC Thinking', prompt: 'Best practice before replacing a part is to:', choices: ['Test and confirm root cause', 'Order parts first', 'Clear codes repeatedly', 'Road test with warning lights ignored'], correct: 'Test and confirm root cause', explanation: 'Evidence-based diagnosis prevents comebacks.', difficulty: 'Easy' },
  { category: 'Inspection Logic', prompt: 'During multipoint inspection, prioritize:', choices: ['Safety items first', 'Cosmetic scratches first', 'Stereo presets', 'Key chain color'], correct: 'Safety items first', explanation: 'Brakes/tires/lights are immediate safety concerns.', difficulty: 'Easy' },
  { category: 'Inspection Logic', prompt: 'If customer says \u201cnoise on bumps,\u201d good first step:', choices: ['Duplicate concern on road test', 'Replace struts immediately', 'Clear all modules', 'Flush transmission'], correct: 'Duplicate concern on road test', explanation: 'Verify symptom before any repair plan.', difficulty: 'Medium' },
  { category: 'Shop Safety', prompt: 'Proper shop footwear is:', choices: ['Closed-toe non-slip shoes', 'Flip-flops', 'Sandals', 'Open heel clogs'], correct: 'Closed-toe non-slip shoes', explanation: 'Foot protection helps prevent injury.', difficulty: 'Easy' },
  { category: 'Tools & Equipment', prompt: 'Before using floor jack, always:', choices: ['Chock wheels and set brake', 'Remove battery', 'Bleed clutch', 'Open hood'], correct: 'Chock wheels and set brake', explanation: 'Prevent vehicle movement.', difficulty: 'Easy' },
  { category: 'Vehicle Maintenance', prompt: 'Cabin air filter mainly affects:', choices: ['Cabin airflow and air quality', 'Starter speed', 'Brake fluid condition', 'Wheel torque'], correct: 'Cabin airflow and air quality', explanation: 'It filters incoming HVAC air.', difficulty: 'Easy' },
  { category: 'Fluids', prompt: 'Using wrong oil viscosity can cause:', choices: ['Poor lubrication performance', 'Brighter headlights', 'Longer brake life', 'Higher tire pressure'], correct: 'Poor lubrication performance', explanation: 'Use manufacturer-specified viscosity.', difficulty: 'Medium' },
  { category: 'Tires', prompt: 'Tire placard pressure info is usually found:', choices: ['Driver door jamb label', 'Windshield top edge', 'Radiator support only', 'Battery case'], correct: 'Driver door jamb label', explanation: 'Placard lists OEM recommended pressures.', difficulty: 'Easy' },
  { category: 'Brakes Basics', prompt: 'Brake pulsation during stops may indicate:', choices: ['Rotor variation/runout', 'Fresh fluid', 'Strong battery', 'Worn spark plugs'], correct: 'Rotor variation/runout', explanation: 'Rotor issues can cause pedal pulsation.', difficulty: 'Medium' },
  { category: 'Batteries', prompt: 'Load testing evaluates battery ability to:', choices: ['Deliver current under load', 'Increase voltage above 15V', 'Cool starter', 'Lubricate terminals'], correct: 'Deliver current under load', explanation: 'Checks voltage behavior while current demand applied.', difficulty: 'Medium' },
  { category: 'Starting Basics', prompt: 'Neutral safety switch prevents cranking when:', choices: ['Transmission is in gear', 'Fuel is low', 'TPMS is on', 'Headlights are bright'], correct: 'Transmission is in gear', explanation: 'Cranking allowed only in safe selector positions.', difficulty: 'Easy' },
  { category: 'Charging Basics', prompt: 'Loose serpentine belt may cause:', choices: ['Low alternator output', 'Better fuel trim', 'Steady overheating only', 'No electrical effect'], correct: 'Low alternator output', explanation: 'Alternator spins slower when belt slips.', difficulty: 'Easy' },
  { category: 'Basic Electrical', prompt: 'High resistance connection is best found by:', choices: ['Voltage drop test under load', 'Visual only', 'Fuel pressure gauge', 'Tire tread depth test'], correct: 'Voltage drop test under load', explanation: 'Loaded voltage drop reveals unwanted resistance.', difficulty: 'Medium' },
  { category: 'Cooling Basics', prompt: 'Electric cooling fan is usually controlled by:', choices: ['ECM and relay logic', 'Horn switch', 'Wiper motor', 'Fuel gauge'], correct: 'ECM and relay logic', explanation: 'Fan command is based on coolant temp inputs.', difficulty: 'Medium' },
  { category: 'Belts & Hoses', prompt: 'When replacing belt, also inspect:', choices: ['Tensioner and pulleys', 'Seat fabric', 'Floor mats', 'Radio antenna'], correct: 'Tensioner and pulleys', explanation: 'Worn tensioners/pulleys shorten new belt life.', difficulty: 'Easy' },
  { category: 'DTC Basics', prompt: 'Best step after reading a code is:', choices: ['Look up info and verify concern', 'Replace first listed part', 'Disconnect battery overnight', 'Ignore if car starts'], correct: 'Look up info and verify concern', explanation: 'Code is a clue, not a parts list.', difficulty: 'Easy' }
];


const ROUND_SECONDS = 60;
const DECISION_SECONDS = 14;
const FEEDBACK_DELAY = 1200;

const MODE_LABELS = {arcade:'Arcade Sprint',daily:'Daily Service Challenge',survival:'Survival Run',category:'Category Practice'};

const els = Object.fromEntries([
  'start-screen','game-screen','result-screen','mode-select','category-select','start-btn','round-timer','question-timer','xp','combo','status-label','status-value','boost-meter','progress-meter','mode-label','question-text','answer-lanes','feedback','end-round-btn','countdown','combo-callout','playfield','final-xp','final-accuracy','final-correct','final-attempted','final-combo','final-rank','final-mode','share-result','copy-result-btn','play-again-btn','change-mode-btn','copy-status'
].map(id=>[id,document.getElementById(id)]));

const categories=[...new Set(questionBank.map(q=>q.category))];
categories.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;els['category-select'].appendChild(o);});

let state={roundTick:null,qTick:null,countdownTick:null,nextQuestionTimer:null,endGameTimer:null,gameActive:false};
const shuffle=a=>[...a].sort(()=>Math.random()-0.5);
function seededShuffle(array,seed){const r=[...array];let s=seed;for(let i=r.length-1;i>0;i--){s=(s*9301+49297)%233280;const j=Math.floor((s/233280)*(i+1));[r[i],r[j]]=[r[j],r[i]];}return r;}
const seedFromDate=()=>{const d=new Date();return Number(`${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,'0')}${String(d.getUTCDate()).padStart(2,'0')}`)};

function pickPool(mode,cat){if(mode==='daily')return seededShuffle(questionBank,seedFromDate());if(mode==='category')return shuffle(questionBank.filter(q=>q.category===cat));return shuffle(questionBank);}
function clearGameTimers(){clearInterval(state.roundTick);clearInterval(state.qTick);clearInterval(state.countdownTick);clearTimeout(state.nextQuestionTimer);clearTimeout(state.endGameTimer);}
function startGame(){clearGameTimers();const mode=els['mode-select'].value;const category=els['category-select'].value;state={mode,category,pool:pickPool(mode,category),xp:0,combo:0,bestCombo:0,correct:0,attempted:0,boost:0,damage:0,lives:mode==='survival'?3:null,idx:0,roundLeft:ROUND_SECONDS,qLeft:DECISION_SECONDS,accepting:false,roundTick:null,qTick:null,countdownTick:null,nextQuestionTimer:null,endGameTimer:null,gameActive:false};els['start-screen'].classList.add('hidden');els['result-screen'].classList.add('hidden');els['game-screen'].classList.remove('hidden');els['mode-label'].textContent=`Mode: ${MODE_LABELS[mode]}`;updateHud();beginCountdown();}

function beginCountdown(){els.countdown.classList.remove('hidden');let n=3;els.countdown.textContent=n;state.countdownTick=setInterval(()=>{n--;if(n>0){els.countdown.textContent=n;return;}if(n===0){els.countdown.textContent='Go!';return;}clearInterval(state.countdownTick);state.countdownTick=null;els.countdown.classList.add('hidden');state.gameActive=true;startRoundTimers();nextQuestion();},500);}
function startRoundTimers(){clearInterval(state.roundTick);state.roundTick=setInterval(()=>{state.roundLeft=Math.max(0,state.roundLeft-1);updateHud();if(state.roundLeft<=0)endGame();},1000);}
function nextQuestion(){if(!state.gameActive)return;clearInterval(state.qTick);state.current=state.pool[state.idx%state.pool.length];state.idx++;state.qLeft=DECISION_SECONDS;state.answered=false;state.accepting=true;renderQuestion();state.qTick=setInterval(()=>{state.qLeft=Math.max(0,state.qLeft-0.1);if(state.qLeft<=0){clearInterval(state.qTick);state.qTick=null;handleAnswer(null,true);}updateHud();},100);updateHud();}
function renderQuestion(){els['question-text'].textContent=state.current.prompt;els['answer-lanes'].innerHTML='';els.feedback.className='feedback';els.feedback.textContent='';els['combo-callout'].textContent='';const choices=shuffle(state.current.choices).slice(0,4).map(t=>({text:t,isCorrect:t===state.current.correct}));state.currentChoices=choices;choices.forEach((c,i)=>{const b=document.createElement('button');b.className=`lane-card lane-${i}`;b.textContent=`${i+1}. ${c.text}`;b.dataset.correct=c.isCorrect;b.style.animation=`fall ${DECISION_SECONDS}s linear forwards`;b.onclick=()=>handleAnswer(i,false);els['answer-lanes'].appendChild(b);});}
function handleAnswer(i,timeout){if(!state.accepting)return;state.accepting=false;clearInterval(state.qTick);state.attempted++;const chosen=i===null?null:state.currentChoices[i];const correctChoice=state.currentChoices.find(c=>c.isCorrect);if(chosen&&chosen.isCorrect){const speed=Math.round((state.qLeft/DECISION_SECONDS)*50);let gain=100+speed;state.correct++;state.combo++;state.bestCombo=Math.max(state.bestCombo,state.combo);if(state.combo%3===0){gain+=75;els['combo-callout'].textContent=`Combo x${state.combo}`;}if(state.combo%5===0){els['combo-callout'].textContent='Boost! Perfect Service!';}
state.xp+=gain;state.boost=Math.min(100,state.boost+10);els.feedback.className='feedback good correct-pop';els.feedback.textContent=`Correct! +${gain} XP. ${state.current.explanation}`;}
else{state.combo=0;if(state.mode==='survival'){state.lives--;if(state.lives<=0){state.lives=0;}}
else{state.damage=Math.min(100,state.damage+18);}els.playfield.classList.add('wrong-shake','flash-red');setTimeout(()=>els.playfield.classList.remove('wrong-shake','flash-red'),280);const prefix=timeout?'Timeout!':'Incorrect!';els.feedback.className='feedback bad';els.feedback.textContent=`${prefix} Correct lane: ${correctChoice.text}. ${state.current.explanation}`;}
updateHud();if(state.mode==='survival'&&state.lives<=0){state.endGameTimer=setTimeout(endGame,FEEDBACK_DELAY);return;}state.nextQuestionTimer=setTimeout(()=>{if(state.gameActive&&state.roundLeft>0)nextQuestion();},FEEDBACK_DELAY);}
function updateHud(){els['round-timer'].textContent=state.roundLeft;els['question-timer'].textContent=state.qLeft.toFixed(1);els.xp.textContent=state.xp;els.combo.textContent=state.combo;if(state.mode==='survival'){els['status-label'].firstChild.textContent='Lives: ';els['status-value'].textContent=state.lives;}else{els['status-label'].firstChild.textContent='Damage: ';els['status-value'].textContent=`${state.damage}%`;}
els['boost-meter'].value=state.boost;els['progress-meter'].value=state.attempted?Math.round((state.correct/state.attempted)*100):0;}
function getRank(xp,acc){if(xp>=2200&&acc>=85)return'Master Tech in Training';if(xp>=1700&&acc>=78)return'Service Lane Pro';if(xp>=1300&&acc>=70)return'Diagnostic Rookie';if(xp>=900&&acc>=62)return'Lube Bay Legend';if(xp>=500&&acc>=50)return'Apprentice Tech';return'Needs More Shop Time';}
function endGame(){if(!state.gameActive&&els['game-screen'].classList.contains('hidden'))return;state.gameActive=false;state.accepting=false;clearGameTimers();els.countdown.classList.add('hidden');els['game-screen'].classList.add('hidden');els['result-screen'].classList.remove('hidden');const acc=state.attempted?Math.round((state.correct/state.attempted)*100):0;const rank=getRank(state.xp,acc);els['final-xp'].textContent=state.xp;els['final-accuracy'].textContent=`${acc}%`;els['final-correct'].textContent=state.correct;els['final-attempted'].textContent=state.attempted;els['final-combo'].textContent=state.bestCombo;els['final-rank'].textContent=rank;els['final-mode'].textContent=MODE_LABELS[state.mode];const share=`Torque Rush: Service Lane Sprint
XP: ${state.xp}
Accuracy: ${acc}%
Best Combo: ${state.bestCombo}
Rank: ${rank}
Mode: ${MODE_LABELS[state.mode]}`;els['share-result'].textContent=share;state.share=share;}

els['start-btn'].onclick=startGame;els['end-round-btn'].onclick=endGame;els['play-again-btn'].onclick=startGame;els['change-mode-btn'].onclick=()=>{els['result-screen'].classList.add('hidden');els['start-screen'].classList.remove('hidden');};
els['copy-result-btn'].onclick=async()=>{try{await navigator.clipboard.writeText(state.share||'');els['copy-status'].textContent='Result copied!';}catch{els['copy-status'].textContent='Copy blocked. Select and copy manually from the result box.';}};
document.addEventListener('keydown',e=>{const keys=['1','2','3','4'];if(keys.includes(e.key)){const i=Number(e.key)-1;handleAnswer(i,false);}if(['ArrowLeft','ArrowUp'].includes(e.key))handleAnswer(0,false);if(['ArrowRight','ArrowDown'].includes(e.key))handleAnswer(1,false);});
